name: Bug Report
description: Let me know if something looks broken
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        If you just need help, please use the community forums (https://community.home-assistant.io).
        **NOTE!** I may take me a while to get back to you. Please bear with me!
  - type: textarea
    id: ha_version
    attributes:
      label: Home Assistant Version
      description: Check your Home Assistant Version in _Settings > About_
      value: |
        Core: eg 2025.5.3
        Frontend: eg 20250516.0
    validations:
      required: true
  - type: textarea
    id: client_version
    attributes:
      label: Browser / App Version
      description: Are you using a browser or the companion app? What version?
      value: |
        Browser: eg Companion app / Chrome / Safari etc
        Browser / app version: eg 2025.5 (2025.1264)
    validations:
      required: true
  - type: textarea
    id: what_i_am_doing
    attributes:
      label: What I am doing
  - type: textarea
    id: what_i_expect_to_happen
    attributes:
      label: What I expect to happen
  - type: textarea
    id: what_happened_instead
    attributes:
      label: What happened instead
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce
      value: |
        1.
        2.
        3.
        ...
  - type: textarea
    id: minimal_code
    attributes:
      label: Include the YAML code you are using with the ring-tile card causing trouble
      placeholder: |
        type: custom:ring-tile
        entity: sensor.temperature  
      render: YAML
  - type: textarea
    id: console_errors
    attributes:
      label: Error messages from the browser console
      description: If you are seeing browser console errors, paste them here
      placeholder: Paste console errors
      render: console