name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pre check
        run: ls -al /home/runner/work/ring-tile-card/ring-tile-card/

      - name: Build
        run: |
          cd /home/runner/work/ring-tile-card/ring-tile-card
          npm install
          npm run build

      - name: Post check
        run: ls -al /home/runner/work/ring-tile-card/ring-tile-card/dist/